Repository himatifdevteam/himatif, pull requests merged in 2023-06, with the labels that each got.

#1 improvement: update readme
  README.md
Labels: documentation

#2 improvement: update add bot
  .github/dependabot.yml
  .github/workflows/main.yml
Labels: documentation

#3 improve: add design pattern
  components/atoms/index.ts
  components/index.ts
  components/modules/index.ts
  components/organisms/index.ts
  libs/auth/index.ts
  libs/index.ts
  libs/provider/index.ts
  modules/common/index.ts
  modules/index.ts
Labels: documentation

#5 improvement: add husky
  .husky/pre-commit
Labels: documentation

#13 add features | components-inputs-text
  app/page.tsx
  components/molecules/index.ts
  components/molecules/inputs/index.ts
  components/molecules/inputs/text/index.tsx
  components/molecules/inputs/text/types.ts
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#16 improvement: add text field
  app/about/page.tsx
  app/layout.tsx
  app/page.tsx
  components/molecules/inputs/text/index.tsx
  components/molecules/inputs/text/types.ts
  components/organisms/navbar/index.tsx
  libs/auth/api.ts
  libs/auth/index.ts
  libs/auth/types.ts
  libs/provider/auth.tsx
  libs/provider/index.ts
  libs/provider/query.tsx
  libs/provider/recoil.tsx
  nextauth.d.ts
  package-lock.json
  package.json
  services/index.ts
  yarn.lock
Labels: bug
